allowBuilds:
  '0': '@'
  '1': g
  '2': o
  '3': o
  '4': g
  '5': l
  '6': e
  '7': /
  '8': g
  '9': e
  '10': n
  '11': a
  '12': i
  '13': =
  '14': t
  '15': r
  '16': u
  '17': e
  '18': ','
  '19': ' '
  '20': p
  '21': r
  '22': o
  '23': t
  '24': o
  '25': b
  '26': u
  '27': f
  '28': j
  '29': s
  '30': =
  '31': t
  '32': r
  '33': u
  '34': e
  '@google/genai': true
  protobufjs: true
onlyBuiltDependencies: '@google/genai, protobufjs'
