import { ShieldAlert } from 'lucide-react';

export function AIDisclaimer() {
  return (
    <div className="flex items-start gap-3 rounded-xl border border-amber-200 bg-amber-50 px-4 py-3">
      <ShieldAlert className="mt-0.5 h-4 w-4 shrink-0 text-amber-600" />
      <p className="text-xs leading-relaxed text-amber-800">
        <span className="font-bold">AI-Assisted Output — Not a Final Diagnosis.</span>{' '}
        This result is generated by the UroLens Smart Diagnosis engine and is intended to
        support, not replace, the clinical judgement of a qualified laboratory professional.
        All findings must be reviewed and confirmed by an authorized Medical Technologist
        or Pathologist before release.
      </p>
    </div>
  );
}
